### ISSUE TITLE
False negatives for backup-archives

### ISSUE THREAD

**Issue by Nanowires** [hannob/snallygaster#42]
I was testing the backup-archives test with a local nginx server. The Server had an (empty) backup.zip file accessible (localhost/backup.zip).
But the backup-archive test didn't print anything.
In the source code, I've found, that you're checking the return code against "b'PK'" for .zip or b'\x1f\x8b\x08' for tar.gz.
I didn't dig too much into the source code, so could you explain these magic numbers?
And wouldn't it be simpler to test with "returnsize=True" and just check if the size isn't 0? By that the test passes for my local nginx test server.

Nice tool BTW ;-)

Best regards

**Comment by hannob** [comment]
This is intentional. These magic numbers actually verify that what you're downloading is a zip (or .tar.gz or whatever) file. So if you place an empty backup.zip it won't detect it.

The background is that you have all kinds of server behavior where some servers won't send error codes, but will just answer every request with something. Avoiding false positives here is tricky, but ultimately what I found most reliable is checking if the data we get is actually of the type of data we expect.

**Comment by Nanowires** [comment]
Thanks for the clarification.
