### ISSUE TITLE
useragent?

### ISSUE THREAD

**Issue by drwetter** [hannob/snallygaster#44]
Hi Hanno,

was just trying to make it more "friendly" wrt WAFs/IDs. 

I realized that independent how I call snallygaster I spot no user-agent in the server side logs. Only the OPTIONS call includes either the preconfigured or the supplied user-agent.

Dirk

**Comment by hannob** [comment]
After chatting directly with the bug reporter we believe this is a problem on his system. We couldn't entirely track it down, but it may be due to an older version of urllib3 that doesn't support passing headers to the poolmanager. If anyone else is affected I recommend running snallygaster with a current version of urllib3.

**Comment by drwetter** [comment]
Itn my case it was urllib3 1.22 which I was using which probably wasn't supporting this.
