### ISSUE TITLE
test_invalidsrc picks the to be tested src url at random

### ISSUE THREAD

**Issue by mphilipps** [hannob/snallygaster#47]
hi,
In line 513 the list of src urls is turned into a set, which mean the order for iterating over the elements afterwards is random/implementation specific. This seems have been done intentional, I however can't see why.

Right now this means calling snallygaster twice against the same server, serving static html files may lead to different results.

**Comment by hannob** [comment]
Interesting...

This wasn't intentional, it is a sideeffect of using a set for the urls, which I do merely to make them unique (we don't want to check the same reference multiple times).

It seems a python set has the property of being unordered (due to randomization, which is to counter hashdos attacks). I've added code to convert the set back to a list and sort it. This should make things deterministic. I find the code a bit workaround-ish, happy to hear better ideas how to do this.

https://github.com/hannob/snallygaster/commit/0e29be547a3022cf6950c668de8c257734999fba
